# -*- mode: python ; coding: utf-8 -*-
# Pyinstaller spec file.
# This file was initially generated by `pyi-makespec --onefile datamart.py`
# and later edited.

from PyInstaller.utils.hooks import copy_metadata
import sys
from os import path
site_packages = next(p for p in sys.path if 'site-packages' in p)

def copy_package(name):
    return [(path.join(site_packages, name), name)]

block_cipher = None

a = Analysis(['datamart.py'],
             pathex=['/mnt/d/Sources/Pedro/datamart/datamart-api'],
             binaries=[],
             datas=copy_metadata("pycountry") + copy_package('distributed') + [('metadata', 'metadata'), ('config.py', '.')],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='datamart',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True )
