version: '3.7'

services:
  db:
    image: postgres:11
    restart: always
    container_name: datamart-empty-postgres
    shm_size: 2gb
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=wikidata
    volumes:
      - ../dev-env/data/postgres:/backup
    expose:
      - "5432"
    ports:
      - "5433:5432"

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: datamart-backend-with-init
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=wikidata
      - POSTGRES_PORT=5432
    expose:
      - "80"
    ports:
      - "12543:80"


# Use internal Docker presistent volumes for Postgres storage, as Windows is having issues with mounting
# local folders as Postgres data folders

# volumes:
#   postgres:
#     name: datamart-postgres-base-volume
